flask-udemy-tutorial/company_blog_site/puppycompanyblog/__init__.py
from flask import Flask 

app = Flask(__name__)



from puppycompanyblog.core.views import core
from puppycompanyblog.error_pages.handlers import error_pages
app.register_blueprint(core)
app.register_blueprint(error_pages)

flask-udemy-tutorial/company_blog_site/puppycompanyblog/core/views.py
from flask import render_template,request,Blueprint

core = Blueprint('core',__name__)

@core.route('/')
def index():
    # MORE TO COME!
    return render_template('index.html')

@core.route('/info')
def info():
    return render_template('info.html')

flask-udemy-tutorial/company_blog_site/puppycompanyblog/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <ul class='nav'>
      <li class='nav-link'>
        <a href="{{url_for('core.index')}}">Home</a>
      </li>
      <li class='nav-link'>
        <a href="{{url_for('core.info')}}">About</a>
      </li>

      <li class='nav-link'>
        <a href="#">Log Out</a>
      </li>
      <li class='nav-link'>
        <a href="#">Account</a>
      </li>
      <li class='nav-link'>
        <a href="#">Create Post</a>
      </li>

      <li class='nav-link'>
        <a href="#">Log In</a>
      </li>
      <li class='nav-link'>
        <a href="#">Register</a>
      </li>
    </ul>
<div class="container">
  {% block content %}

  {% endblock %}
</div>


  </body>
</html>

flask-udemy-tutorial/company_blog_site/puppycompanyblog/templates/index.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>Puppy Company Blog</h1>
  </div>
{% endblock %}

flask-udemy-tutorial/company_blog_site/puppycompanyblog/templates/info.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>Info about our company</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
{% endblock %}